dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

addons:
  apt:
    packages:
      - pandoc
      #
      - python-h5py
      - python-matplotlib
      - python-numpy
      - python-scipy
      #
      - python3-h5py
      - python3-matplotlib
      - python3-numpy
      - python3-scipy

before_install:
  - pip install pytest pytest-cov

install:
  - pip install .

script:
  - cd tests && MPLBACKEND=Agg pytest --cov voropy

after_success:
  - bash <(curl -s https://codecov.io/bash)
